### ISSUE TITLE
If console is turned off, Jenkinsfile setup still contains `ws enable console`

### ISSUE THREAD

**Issue by kierenevans** [inviqa/harness-docker#7]
In https://github.com/inviqa/harness-docker/blob/main/application/overlay/_twig/Jenkinsfile/setup.twig, need to make `ws enable console` be `ws enable` if services.console.enabled is false.

**Comment by andytson-inviqa** [comment]
you effectively need jenkins.tests.isolated to be off when console is disabled, as there is no isolation otherwise, as everything is done up front in `ws enable`

**Comment by kierenevans** [comment]
Yeah even `ws install` fails without harness/scripts/enabled.sh.twig changes. Will close :+1:

**Comment by andytson-inviqa** [comment]
I think enabled.sh.twig needs to be changed in any case. I sort of want `ws enable/disable` to be renamed as it conflicts with the idea of service enable, `ws start/pause` i guess

**Comment by kierenevans** [comment]
Could alias `start` to `enable`, `stop` to `disable` like in https://github.com/my127/workspace/blob/0.2.x/home/service/tracing/init.sh#L9-L22 ?
